# production defaults
# see the `dev` profile below for development

app:
  vaadin:
    productionMode: "false" # we always need devmode because of the SASS compiler; must be string!

vaadin:
  servlet:
    params:
      productionMode: "${app.vaadin.productionMode}"
  # see https://github.com/peholmst/vaadin4spring/issues/108#issuecomment-69953039
  static:
    servlet:
      params:
        productionMode: "${app.vaadin.productionMode}"

spring:
  groovy:
    template:
      check-template-location: false

logging:
  level:
    vdecl: DEBUG
    com: WARN
    org: WARN

watch: ./ # directory to watch
interval: 250 # interval in ms passed to the file alteration monitor

---

spring:
    profiles: dev

watch: ./examples
